name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'

      - run: npm install --frozen-lockfile
      - run: npm run ci
